var subElectrica = {
"type": "FeatureCollection",
"name": "SubestacionEnergiaElectrica",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "nom_estab": "SUBESTACION MINATITLAN UNO CFE", "raz_social": "COMISIÓN FEDERAL DE ELECTRICIDAD", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "31 a 50 personas", "tipo_vial": "BOULEVARD", "nom_vial": "INSTITUTO TECNOLÓGICO", "tipo_v_e_1": "CALLE", "nom_v_e_1": "TEOTIHUACÁN", "tipo_v_e_2": "CALLE", "nom_v_e_2": "PAPALOAPAN", "tipo_v_e_3": "CALLE", "nom_v_e_3": "BERLÍN", "tipo_asent": "COLONIA", "nomb_asent": "LA FUENTE", "cod_postal": "96729", "cve_ent": "30", "entidad": "VERACRUZ DE IGNACIO DE LA LLAVE", "cve_mun": "108", "municipio": "MINATITLÁN", "cve_loc": "0001", "localidad": "MINATITLÁN", "ageb": "1130", "manzana": "010", "telefono": "9222210419", "correoelec": null, "latitud": 17.9924937, "longitud": -94.57544528, "fecha_alta": "JULIO 2010" }, "geometry": { "type": "Point", "coordinates": [ -94.57544528, 17.9924937 ] } },
{ "type": "Feature", "properties": { "nom_estab": "SUBESTACIÓN DE COMISIÓN FEDERAL DE ELECTRICIDAD", "raz_social": null, "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "BAHÍA SANTA CRUZ", "tipo_v_e_1": "CALLE", "nom_v_e_1": "BAHÍA RISCALILLO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "BAHIA DE SAN AGUSTIN", "tipo_v_e_3": "CALLE", "nom_v_e_3": "CHAHUE", "tipo_asent": "SECTOR", "nomb_asent": "T", "cod_postal": "70989", "cve_ent": "20", "entidad": "OAXACA", "cve_mun": "413", "municipio": "SANTA MARÍA HUATULCO", "cve_loc": "0078", "localidad": "CRUCECITA", "ageb": "0173", "manzana": "007", "telefono": "9585830335", "correoelec": null, "latitud": 15.76991243, "longitud": -96.13934111, "fecha_alta": "DICIEMBRE 2014" }, "geometry": { "type": "Point", "coordinates": [ -96.13934111, 15.76991243 ] } },
{ "type": "Feature", "properties": { "nom_estab": "SUBESTACIÓN SAN ANDRÉS 2", "raz_social": "CFE", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "11 a 30 personas", "tipo_vial": "CALLE", "nom_vial": "MANUEL A. DE LA CABADA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "MANUEL A DE LA CABADA", "tipo_v_e_2": "CALLE", "nom_v_e_2": "LAS AZUCENAS", "tipo_v_e_3": "CALLE", "nom_v_e_3": "LAS BUGAMBILIAS", "tipo_asent": "COLONIA", "nomb_asent": "LÓPEZ LARA", "cod_postal": "95736", "cve_ent": "30", "entidad": "VERACRUZ DE IGNACIO DE LA LLAVE", "cve_mun": "141", "municipio": "SAN ANDRÉS TUXTLA", "cve_loc": "0001", "localidad": "SAN ANDRÉS TUXTLA", "ageb": "0599", "manzana": "021", "telefono": "2949421031", "correoelec": "PEDRO.VITCHIS@CFE.GOB.MX", "latitud": 18.44716057, "longitud": -95.23027194, "fecha_alta": "DICIEMBRE 2014" }, "geometry": { "type": "Point", "coordinates": [ -95.23027194, 18.44716057 ] } },
{ "type": "Feature", "properties": { "nom_estab": "SUB ESTACIÓN DE ELECTRICIDAD YOLOMECATL", "raz_social": "COMISIÓN FEDERAL DE ELECTRICIDAD", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "6 a 10 personas", "tipo_vial": "AVENIDA", "nom_vial": "CENTENARIO", "tipo_v_e_1": "CALLE", "nom_v_e_1": "ACATEMPAN", "tipo_v_e_2": "CALLE", "nom_v_e_2": "EJÉRCITO TRIGARANTE", "tipo_v_e_3": "CALLE", "nom_v_e_3": "MORELOS", "tipo_asent": "SECCIÓN", "nomb_asent": "SEGUNDA", "cod_postal": "69570", "cve_ent": "20", "entidad": "OAXACA", "cve_mun": "499", "municipio": "SANTIAGO YOLOMÉCATL", "cve_loc": "0001", "localidad": "SANTIAGO YOLOMÉCATL", "ageb": "0036", "manzana": "003", "telefono": null, "correoelec": null, "latitud": 17.47001285, "longitud": -97.56829973000001, "fecha_alta": "DICIEMBRE 2014" }, "geometry": { "type": "Point", "coordinates": [ -97.56829973, 17.47001285 ] } },
{ "type": "Feature", "properties": { "nom_estab": "SUBESTACION VISTALMAR", "raz_social": "CFE", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "11 a 30 personas", "tipo_vial": "BOULEVARD", "nom_vial": "ANTIGUA A MINATITLÁN", "tipo_v_e_1": "AVENIDA", "nom_v_e_1": "LAS PALMAS", "tipo_v_e_2": "CALLE", "nom_v_e_2": "NAVEGANTES", "tipo_v_e_3": "CALLE", "nom_v_e_3": "FRAMBOYAN", "tipo_asent": "FRACCIONAMIENTO", "nomb_asent": "RANCHO ALEGRE 1", "cod_postal": "96558", "cve_ent": "30", "entidad": "VERACRUZ DE IGNACIO DE LA LLAVE", "cve_mun": "039", "municipio": "COATZACOALCOS", "cve_loc": "0001", "localidad": "COATZACOALCOS", "ageb": "1269", "manzana": "005", "telefono": null, "correoelec": null, "latitud": 18.14104177, "longitud": -94.47017708, "fecha_alta": "JULIO 2010" }, "geometry": { "type": "Point", "coordinates": [ -94.47017708, 18.14104177 ] } },
{ "type": "Feature", "properties": { "nom_estab": "ÁREA DE SUB ESTACIÓN DE CFE", "raz_social": "COMISIÓN FEDERAL DE ELECTRICIDAD", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "0 a 5 personas", "tipo_vial": "CALLE", "nom_vial": "NINGUNO", "tipo_v_e_1": "CALLE", "nom_v_e_1": "NINGUNO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "NUEVO LEÓN", "tipo_v_e_3": "PROLONGACIÓN", "nom_v_e_3": "BOULEVARD MÉXICO", "tipo_asent": "COLONIA", "nomb_asent": "JUAN DÍAZ M0NTALVO", "cod_postal": "95347", "cve_ent": "30", "entidad": "VERACRUZ DE IGNACIO DE LA LLAVE", "cve_mun": "208", "municipio": "CARLOS A. CARRILLO", "cve_loc": "0001", "localidad": "CARLOS A. CARRILLO", "ageb": "0087", "manzana": "007", "telefono": null, "correoelec": null, "latitud": 18.3717015, "longitud": -95.75872463, "fecha_alta": "DICIEMBRE 2014" }, "geometry": { "type": "Point", "coordinates": [ -95.75872463, 18.3717015 ] } },
{ "type": "Feature", "properties": { "nom_estab": "SUBESTACION ELÉCTRICA CARDENAS UNO", "raz_social": "COMISIÓN FEDERAL DE ELECTRICIDAD", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "0 a 5 personas", "tipo_vial": "AVENIDA", "nom_vial": "CIRCUITO DEL GOLFO", "tipo_v_e_1": "CALLE", "nom_v_e_1": "TURQUESA", "tipo_v_e_2": "CARRETERA", "nom_v_e_2": "NINGUNO", "tipo_v_e_3": null, "nom_v_e_3": "NINGUNA", "tipo_asent": "COLONIA", "nomb_asent": "SANTA CRUZ", "cod_postal": "86530", "cve_ent": "27", "entidad": "TABASCO", "cve_mun": "002", "municipio": "CÁRDENAS", "cve_loc": "0001", "localidad": "CÁRDENAS", "ageb": "0733", "manzana": "002", "telefono": null, "correoelec": null, "latitud": 17.99904979, "longitud": -93.39510238, "fecha_alta": "JULIO 2010" }, "geometry": { "type": "Point", "coordinates": [ -93.39510238, 17.99904979 ] } },
{ "type": "Feature", "properties": { "nom_estab": "SUBESTACIÓN CFE BOCA DEL RÍO", "raz_social": "COMISIÓN FEDERAL DE ELECTRICIDAD", "codigo_act": "221110", "nombre_act": "Generación, transmisión y distribución de energía eléctrica", "per_ocu": "31 a 50 personas", "tipo_vial": "CALLE", "nom_vial": "SAN ANDRÉS TUXTLA", "tipo_v_e_1": "CALLE", "nom_v_e_1": "5 DE FEBRERO", "tipo_v_e_2": "CALLE", "nom_v_e_2": "HIMALAYA", "tipo_v_e_3": "CALLE", "nom_v_e_3": "HIMALAYA", "tipo_asent": "COLONIA", "nomb_asent": "GRACIANO SANCHEZ", "cod_postal": "94293", "cve_ent": "30", "entidad": "VERACRUZ DE IGNACIO DE LA LLAVE", "cve_mun": "028", "municipio": "BOCA DEL RÍO", "cve_loc": "0037", "localidad": "VERACRUZ", "ageb": "0873", "manzana": "039", "telefono": "2299892329", "correoelec": null, "latitud": 19.1169469, "longitud": -96.11005351, "fecha_alta": "DICIEMBRE 2014" }, "geometry": { "type": "Point", "coordinates": [ -96.11005351, 19.1169469 ] } }
]
}
